---
builds:
  - binary: sshbox
    flags: -tags "static_build"
    ldflags: >-
      -w
      -X github.com/prologic/sshbox.Version={{.Version}}
      -X github.com/prologic/sshbox.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
signs:
  - artifacts: checksum
release:
  github:
    owner: prologic
    name: sshbox
  draft: true
